### ISSUE TITLE
In-app console text is white, causing poor readability in light mode

### ISSUE THREAD

**Issue by YaeneZ** [YM-Productions/PSL#6]
**Description:**
In light mode, the in-app console text is rendered in white, making it nearly invisible against the light background. This color choice conflicts with the light theme and prevents users from reading console output.

---

**Steps to Reproduce:**

1. Switch the application to light mode in Settings.
2. Open the in-app console.
3. Type or execute any command.
4. Observe that the output text is white on a light background.

---

**Actual Behavior:**

* Console text appears in white (`#FFFFFF`) on a light-background, resulting in very low contrast and unreadable output.

---

**Expected Behavior:**

* In light mode, console text should use a dark or theme-appropriate color (e.g., `#000000` or a CSS variable) to ensure sufficient contrast and readability.

---

**Environment:**

* Application version: v1.2.3
* Runtime: Electron 25.0.0 / Node.js 18.12.1
* OS: Windows 10 / macOS 13.4 / Ubuntu 22.04
* Theme implementation: CSS variables in `theme.css` and `console.scss`

---

**Possible Fixes:**

* Update the console’s CSS to reference the theme’s text color variable (e.g., `--text-color`) instead of hardcoding white.
* Add a conditional style rule:

  ```css
  .console-output {
    color: var(--console-text-color);
  }
  [data-theme="light"] .console-output {
    --console-text-color: #000000;
  }
  [data-theme="dark"] .console-output {
    --console-text-color: #FFFFFF;
  }
  ```
* Ensure the console’s background and text colors meet WCAG AA contrast requirements for both themes.
